dealer = {
    "city": "Самара",
    "where": "Самаре",
}
# Словарь соответствия цветов
model_mapping = {
    "BJ40": {
        "folder": "bj40",
        "color": {
            "Black": "black.png",
            "Blue": "blue.png",
            "Green": "green.png",
            "Light-blue": "light-blue.png",
            "Red": "red.png",
            "White": "white.png",
            "Черный": "black.png",
            "Синий": "blue.png",
            "Зеленый": "green.png",
            "Светло-синий": "light-blue.png",
            "Голубой": "light-blue.png",
            "Красный": "red.png",
            "Белый": ".pngwhite",
        }},
    "U5 Plus": {
        "folder": "u5-plus",
        "color": {
            "Black": "black.png",
            "Gray": "gray.png",
            "Grey": "gray.png",
            "Red": "red.png",
            "White": "white.png",
            "Черный": "black.png",
            "Серый": "gray.png",
            "Красный": "red.png",
            "Белый": "white.png",
        }},
    "X35": {
        "folder": "x35",
        "color": {
            "Blue": "blue.png",
            "Bronze": "bronze.png",
            "Red": "red.png",
            "Silver": "silver.png",
            "White": "white.png",
            "Синий": "blue.png",
            "Коричневый": "bronze.png",
            "Серебрисный": "silver.png",
            "Серебряный": "silver.png",
            "Красный": "red.png",
            "Белый": "white.png",
        }},
    "X55": {
        "folder": "x55",
        "color": {
            "Gray-with-black-roof": "gray-with-black-roof.png",
            "Gray": "gray.png",
            "Grey": "gray.png",
            "Light-gray-with-black-roof": "light-gray-with-black-roof.png",
            "Light-gray": "light-gray.png",
            "Red-with-black-roof": "red-with-black-roof.png",
            "Red": "red.png",
            "White-with-black-roof": "white-with-black-roof.png",
            "White": "white.png",
            "Yellow-with-black-roof": "yellow-with-black-roof.png",
            "Yellow": "yellow.png",
            "Серый": "gray.png",
            "Серый/черный": "gray-with-black-roof.png",
            "Светло-серый/черный": "light-gray-with-black-roof.png",
            "Светло-серый": "light-gray.png",
            "Красный/черный": "red-with-black-roof.png",
            "Красный": "red.png",
            "Белый/черный": "white-with-black-roof.png",
            "Белый": "white.png",
            "Желтый/черный": "yellow-with-black-roof.png",
            "Желтый": "yellow.png",
        }},
    "X7": {
        "folder": "x7",
        "color": {
            "Black": "black.png",
            "Gray": "gray.png",
            "Grey": "gray.png",
            "Silver": "silver.png",
            "White": "white.png",
            "Черный": "black.png",
            "Серый": "gray.png",
            "Серебристый": "silver.png",
            "Белый": "white.png",
        }},
    "X75": {
        "folder": "x75",
        "color": {
            "Black": "black.webp",
            "Черный": "black.webp",
            "Blue-black": "blue-black.webp",
            "Сине-черный": "blue-black.webp",
            "Blue": "blue.webp",
            "Голубой": "blue.webp",
            "Dark-gray-black": "dark-gray-black.webp",
            "Темно-серо-черный": "dark-gray-black.webp",
            "Dark-gray": "dark-gray.webp",
            "Темно-серый": "dark-gray.webp",
            "Серый": "dark-gray.webp",
            "Red-black": "red-black.webp",
            "Красно-черный": "red-black.webp",
            "Red": "red.webp",
            "Красный": "red.webp",
            "Silver-black": "silver-black.webp",
            "Серебристо-черный": "silver-black.webp",
            "Silver": "silver.webp",
            "Серебристый": "silver.webp",
            "White-black": "white-black.webp",
            "Бело-черный": "white-black.webp",
            "White": "white.webp",
            "Белый": "white.webp",
        }},
    # ... добавьте другие модели по мере необходимости
}