import './modules/scroll';
import '/node_modules/scripts/js/analytics.js';
import './modules/slider';
import './modules/functions';
import './modules/color.links';
import './modules/map';
import './modules/form';
import './modules/modals';
import './modules/btn.up';
